### ISSUE TITLE
XMLHttpRequest cannot load 

### ISSUE THREAD

**Issue by zhouwenbin** [XristMisyris/quasar-starter-frontend#1]
http://localhost:8000/api/v1/authenticate. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

**Comment by XristMisyris** [comment]
Hello. I am using [this](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi/reviews?hl=en) chrome extension for developing on localhost. Just turn on this addon when you are getting errors. Dont forget to turn off the addon after you are done with developing, because you will face some isues with facebook chat, dropbox etc...

**Comment by zhouwenbin** [comment]
XMLHttpRequest cannot load http://localhost:8000/api/v1/register. Response for preflight has invalid HTTP status code 404

**Comment by XristMisyris** [comment]
Did you turned on the extension ?

![cors](http://i.imgur.com/9rHaP45.png)

**Comment by zhouwenbin** [comment]
yes

**Comment by zhouwenbin** [comment]
can work,thanks
